[build-system] # Require setuptool version due to https://github.com/pypa/setuptools/issues/2938
requires = ["setuptools>=61.0.0", "wheel"]

[project]
name = "pulsex"
version = "0.1.0"
description = "Next generation cardiac mechanics solver based on FEniCSx"
authors = [{name = "Henrik Finsberg", email = "henriknf@simula.no"}]
license = {file = "LICENSE"}
readme = "README.md"

[project.scripts]
pulsex = "pulsex.cli:main"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]
dev = [
    "pdbpp",
    "ipython",

    "pre-commit",
]
docs = [
   "jupyter-book",
   "jupytext",
]

all = [
   "pulsex[test]",
   "pulsex[docs]",
   "pulsex[dev]",
]

[tool.pytest.ini_options]
addopts = [
   "--import-mode=importlib",
   "--cov=pulsex",
   "--cov-report=html",
   "--cov-report=term-missing",
   "-v"
]
testpaths = [
    "tests"
]
